/**
 * FarmFlow AI — Business Impact & KPI Calculation Engine
 * --------------------------------------------------------
 * Computes transparent, measurable business and environmental KPIs
 * derived directly from the 4-agent pipeline outputs.
 */

export function calculateFarmImpact(pipeline, submittedInput = {}) {
  const farmsense = pipeline?.farmsense || {};
  const cropguard = pipeline?.cropguard || {};
  const marketmind = pipeline?.marketmind || {};

  const expectedYield = Number(cropguard.expected_yield_kg) || 0;
  const marketDemand = Number(submittedInput.market_demand || marketmind.market_demand_kg) || 0;

  // 1. Water Saved (L)
  const waterSavedL = Number(farmsense.water_saved_l) || 0;

  // 2. Produce Rescued (kg)
  const produceRescuedKg = Number(marketmind.food_rescued_kg) || 0;

  // 3. Economic Value Recovered (₹)
  const economicValueRecovered = Number(marketmind.economic_value_recovered_inr) || 0;

  // 4. Economic Value at Risk (₹)
  const economicValueAtRisk = Number(marketmind.economic_value_at_risk_inr) || 0;

  // 5. Waste Avoided (kg)
  const wasteAvoidedKg = Number(marketmind.waste_avoided_kg) || 0;

  // 6. Market Demand Fulfillment (%)
  let demandFulfillmentPct = 100.0;
  if (marketDemand > 0 && expectedYield > 0) {
    // Fulfilled quantity is commercial allocation up to market demand
    const commercialAllocated = Math.min(expectedYield, marketDemand);
    demandFulfillmentPct = Math.min(100.0, Math.round((commercialAllocated / marketDemand) * 1000) / 10);
  }

  // 7. Estimated Farmer Benefit (₹)
  // Formula: Economic Value Recovered (rescued produce) + Pumping Energy & Input Water Savings (₹0.15/L)
  const waterCostPerLiter = 0.15; // Average canal/borewell pumping electricity cost per litre in TN
  const waterPumpingSavings = Math.round(waterSavedL * waterCostPerLiter);
  const estimatedFarmerBenefit = Math.round(economicValueRecovered + waterPumpingSavings);

  // 8. Estimated Operational Time Saved (hrs / cycle)
  // Transparent derivation: 1.5 hrs saved on manual soil/weather checks + 1.0 hr saved on manual mandi matching
  const estimatedTimeSavedHrs = 2.5;

  return {
    waterSavedL,
    produceRescuedKg,
    economicValueRecovered,
    economicValueAtRisk,
    wasteAvoidedKg,
    expectedYield,
    marketDemand,
    demandFulfillmentPct,
    estimatedFarmerBenefit,
    waterPumpingSavings,
    estimatedTimeSavedHrs,
  };
}

export const KPI_METADATA = [
  {
    key: 'waterSavedL',
    label: 'WATER SAVED',
    unit: 'L',
    source: 'FARMSENSE (நிலம்)',
    badgeColor: '#6F956B',
    explanation: 'Estimated canal and irrigation water conserved based on rain forecast and soil moisture deferral.',
    formula: 'Water Saved = FarmSense Base Irrigation Usage × Crop Stage Multiplier (when rain delay active)',
    isEstimated: true,
  },
  {
    key: 'produceRescuedKg',
    label: 'PRODUCE RESCUED',
    unit: 'KG',
    source: 'MARKETMIND (சந்தை)',
    badgeColor: '#C7A45A',
    explanation: 'Perishable surplus volume successfully matched to state civil supplies, food banks, and NGOs.',
    formula: 'Produce Rescued = Min(Surplus Yield, Alternative Rescue Channel Capacity)',
    isEstimated: true,
  },
  {
    key: 'economicValueRecovered',
    label: 'VALUE RECOVERED',
    unit: '₹',
    source: 'MARKETMIND (சந்தை)',
    badgeColor: '#C7A45A',
    explanation: 'Direct monetary value of rescued produce diverted from waste at current market prices.',
    formula: 'Value Recovered = Produce Rescued (kg) × Market Price (₹/kg)',
    isEstimated: true,
  },
  {
    key: 'economicValueAtRisk',
    label: 'VALUE AT RISK',
    unit: '₹',
    source: 'MARKETMIND (சந்தை)',
    badgeColor: '#8F3E3E',
    explanation: 'Financial value of unallocated surplus yield exceeding regional market demand and rescue capacity.',
    formula: 'Value at Risk = Unallocated Surplus (kg) × Market Price (₹/kg)',
    isEstimated: true,
  },
  {
    key: 'wasteAvoidedKg',
    label: 'WASTE AVOIDED',
    unit: 'KG',
    source: 'MARKETMIND (சந்தை)',
    badgeColor: '#6F956B',
    explanation: 'Produce diverted away from organic landfill decomposition and post-harvest spoilage.',
    formula: 'Waste Avoided = Total Harvest Rescued & Redirected to Consumption',
    isEstimated: true,
  },
  {
    key: 'expectedYield',
    label: 'ESTIMATED YIELD',
    unit: 'KG',
    source: 'CROPGUARD (வளம்)',
    badgeColor: '#6F956B',
    explanation: 'Total predicted crop harvest volume generated by CropGuard Random Forest ML model.',
    formula: 'ML Yield Prediction = RandomForestRegressor(soil_moisture, temp, humidity, crop, stage)',
    isEstimated: true,
  },
  {
    key: 'demandFulfillmentPct',
    label: 'DEMAND FULFILLMENT',
    unit: '%',
    source: 'MARKETMIND & CROPGUARD',
    badgeColor: '#E8E3D5',
    explanation: 'Percentage of target commercial market demand satisfied by predicted harvest.',
    formula: 'Demand Fulfillment % = Min(100%, (Commercial Allocated Yield / Target Market Demand) × 100)',
    isEstimated: true,
  },
  {
    key: 'estimatedFarmerBenefit',
    label: 'FARMER BENEFIT',
    unit: '₹',
    source: 'FARMSENSE & MARKETMIND',
    badgeColor: '#C7A45A',
    explanation: 'Combined monetary value gained from rescued surplus produce and conserved irrigation pumping electricity.',
    formula: 'Farmer Benefit = Economic Value Recovered (₹) + (Water Saved (L) × ₹0.15/L Pumping Cost)',
    isEstimated: true,
  },
  {
    key: 'estimatedTimeSavedHrs',
    label: 'TIME SAVED',
    unit: 'HRS',
    source: 'FARMFLOW AUTOMATION',
    badgeColor: '#6F956B',
    explanation: 'Operational hours saved per cycle by automating moisture sensing, weather monitoring, and mandi matching.',
    formula: 'Time Saved = ~1.5h Field Inspection + ~1.0h Mandi Channel Matching per Irrigation Cycle',
    isEstimated: true,
  },
];
